# -*- coding: utf-8 -*-
"""bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0PTIeM5Mlif9p01csbfsSwaVJySTzC5
"""

import requests
from telegram import Update
from telegram.ext import Application, CommandHandler, CallbackContext

# Replace with your actual tokens
BOT_TOKEN = "8072102060:AAEynutkU-lVNIhgcOO_PWhh7zRfNa7VYEA"
NEWS_API_KEY = "7501a72bbbe84608baa791f79335ef6b"

# Function to fetch crypto news
def get_crypto_news():
    url = f"https://newsapi.org/v2/everything?q=crypto&apiKey={NEWS_API_KEY}"
    response = requests.get(url).json()

    articles = response.get("articles", [])[:5]  # Get top 5 news articles
    news_list = [f"{article['title']}\n{article['url']}" for article in articles]

    return "\n\n".join(news_list) if news_list else "No news available."

# Command to send news
async def send_news(update: Update, context: CallbackContext):
    news = get_crypto_news()
    await update.message.reply_text(news)

# Start command
async def start(update: Update, context: CallbackContext):
    await update.message.reply_text("Welcome! Use /news to get the latest crypto news.")

# Main function
def main():
    app = Application.builder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("news", send_news))
    app.run_polling()

if __name__ == "__main__":
    main()